"""empty message

Revision ID: 011bd7bedbe2
Revises: 48c50acebc89
Create Date: 2019-07-19 17:21:21.504189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011bd7bedbe2'
down_revision = '48c50acebc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tittle', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria')
    # ### end Alembic commands ###
