"""empty message

Revision ID: 16c1a64ecd63
Revises: bf1e7cb25ad8
Create Date: 2019-08-07 15:49:34.687532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c1a64ecd63'
down_revision = 'bf1e7cb25ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint('entrada_id_categoria_fkey', 'entrada', type_='foreignkey')
    op.drop_column('entrada', 'id_categoria')
    op.alter_column('movimento', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movimento', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('entrada', sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('entrada_id_categoria_fkey', 'entrada', 'categoria', ['id_categoria'], ['id'])
    op.drop_table('users')
    # ### end Alembic commands ###
