"""empty message

Revision ID: 621ae30c5716
Revises: 92e8411803e9
Create Date: 2019-08-07 22:49:29.211413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621ae30c5716'
down_revision = '92e8411803e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
