"""empty message

Revision ID: bf1e7cb25ad8
Revises: d1a77e3e3722
Create Date: 2019-07-23 20:23:02.385955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1e7cb25ad8'
down_revision = 'd1a77e3e3722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movimento_saldo_id_fkey', 'movimento', type_='foreignkey')
    op.drop_column('movimento', 'saldo_id')
    op.add_column('saldo', sa.Column('movimento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'saldo', 'movimento', ['movimento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saldo', type_='foreignkey')
    op.drop_column('saldo', 'movimento_id')
    op.add_column('movimento', sa.Column('saldo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movimento_saldo_id_fkey', 'movimento', 'saldo', ['saldo_id'], ['id'])
    # ### end Alembic commands ###
