"""empty message

Revision ID: d1a77e3e3722
Revises: fb328e47127c
Create Date: 2019-07-23 20:05:50.499559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a77e3e3722'
down_revision = 'fb328e47127c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('saida_id', sa.Integer(), nullable=True),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('saldo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrada.id'], ),
    sa.ForeignKeyConstraint(['saida_id'], ['saida.id'], ),
    sa.ForeignKeyConstraint(['saldo_id'], ['saldo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimento')
    op.drop_table('saida')
    op.drop_table('entrada')
    op.drop_table('saldo')
    # ### end Alembic commands ###
